import { tools } from "@/data/tools";
import { categories } from "@/data/categories";
import { getAllComparisonPairs } from "@/lib/comparisons";
import { getToolsWithAlternatives } from "@/lib/alternatives";
import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const base = "https://aisotools.com";
  const now = new Date().toISOString();

  const staticPages = [
    { url: base, lastModified: now, changeFrequency: "daily" as const, priority: 1 },
    { url: `${base}/compare`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.8 },
    { url: `${base}/alternatives`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/submit`, lastModified: now, changeFrequency: "monthly" as const, priority: 0.6 },
    { url: `${base}/advertise`, lastModified: now, changeFrequency: "monthly" as const, priority: 0.7 },
    { url: `${base}/pricing`, lastModified: now, changeFrequency: "monthly" as const, priority: 0.7 },
    { url: `${base}/pricing/tools`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
  ];

  // Standalone comparison pages (not generated dynamically)
  const standaloneComparisons = [
    { url: `${base}/chatgpt-vs-gemini`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/chatgpt-vs-claude`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/midjourney-vs-dall-e`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/cursor-vs-github-copilot`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/grok-vs-chatgpt`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/deepseek-vs-chatgpt`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/copilot-vs-chatgpt`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/perplexity-vs-chatgpt`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/grok-vs-chatgpt-vs-gemini`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/grammarly-vs-quillbot`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/midjourney-vs-runway`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/midjourney-vs-stable-diffusion`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/jasper-vs-copyai`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/claude-vs-gemini`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/cursor-vs-windsurf`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/sora-vs-runway`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/kling-vs-runway`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/github-copilot-vs-claude-code`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/flux-vs-midjourney`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/deepseek-vs-claude`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/claude-code-vs-cursor`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/claude-code-vs-windsurf`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/perplexity-vs-gemini`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/v0-vs-lovable`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/bolt-vs-lovable`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/bolt-vs-v0`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/synthesia-vs-heygen`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/sora-vs-kling`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/notebooklm-vs-chatgpt`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    // Standalone alternatives pages
    { url: `${base}/chatgpt-alternatives`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/claude-alternatives`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/midjourney-alternatives`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/canva-alternatives`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/copilot-alternatives`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/alternatives/dall-e`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/dall-e-alternatives`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/alternatives/windsurf`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/elevenlabs-alternatives`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/github-copilot-alternatives`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/grammarly-alternatives`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/hugging-face-alternatives`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/jasper-alternatives`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/notion-ai-alternatives`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/perplexity-alternatives`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/replicate-alternatives`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/runway-alternatives`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/synthesia-alternatives`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/copyai-alternatives`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/writesonic-alternatives`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/quillbot-alternatives`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/wordtune-alternatives`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/alternatives/deepseek`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/gemini-alternatives`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/alternatives/zapier`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/figma-alternatives`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/alternatives/loom`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/alternatives/tome`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/alternatives/beautiful-ai`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    // Standalone pricing pages
    { url: `${base}/chatgpt-plus-pricing`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/midjourney-pricing`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/jasper-ai-pricing`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/notion-ai-pricing`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/copyai-pricing`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/grammarly-pricing`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/synthesia-pricing`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/runway-ml-pricing`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/elevenlabs-pricing`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/perplexity-pro-pricing`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    // Blog posts
    { url: `${base}/blog/best-ai-tools-for-freelancers-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-crm-tools-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/miro-alternatives-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-collaboration-tools-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-product-managers-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-healthcare-professionals-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-agent-frameworks-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    // Batch 28 blog posts
    { url: `${base}/blog/best-ai-tools-for-academic-research-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-accountants-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-software-architects-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-real-estate-agents-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    // Batch 29 blog posts
    { url: `${base}/blog/best-ai-tools-for-marketing-agencies-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-designers-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-doctors-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-lawyers-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    // aiso-taaft-gaps batch 30: profession blog expansion
    { url: `${base}/blog/best-ai-tools-for-engineers-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-social-media-managers-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-data-scientists-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-photographers-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/compare/claude-vs-perplexity`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/compare/deepseek-vs-perplexity`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/compare/perplexity-vs-youcom`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/compare/midjourney-vs-flux`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/compare/sora-vs-luma-dream-machine`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/compare/chatgpt-vs-claude`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/compare/chatgpt-vs-gemini`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/compare/cursor-vs-github-copilot`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.9 },
    { url: `${base}/compare/elevenlabs-vs-murf-ai`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    // aiso-taaft-gaps use case pages
    { url: `${base}/use-case/ai-for-writing-seo-content`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/use-case/ai-for-video-editing`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/use-case/ai-for-coding-assistants`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/use-case/ai-for-social-media-automation`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/use-case/ai-for-academic-research`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/use-case/ai-for-meeting-summarization`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/use-case/ai-for-customer-support-automation`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/use-case/ai-for-presentation-design`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/use-case/ai-for-voice-cloning`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/use-case/ai-for-data-analysis`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    // aiso-taaft-gaps batch: 5 new blog posts (Apr 24 2026)
    { url: `${base}/blog/best-ai-tools-for-podcasters-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-music-generators-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-copywriters-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-video-editors-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-recruiters-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    // aiso-taaft-gaps sprint Apr 24 2026: 5 new profession blog posts + blog index fix
    { url: `${base}/blog/best-ai-tools-for-financial-advisors-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-journalists-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-musicians-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-architects-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-nonprofits-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    // aiso-taaft-gaps sprint Apr 25 2026: 5 new profession blog posts
    { url: `${base}/blog/best-ai-tools-for-game-developers-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-cybersecurity-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-devops-engineers-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-ux-designers-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-translators-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-nurses-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-therapists-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-personal-trainers-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-voice-generators-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.88 },
    { url: `${base}/blog/best-free-ai-tools-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.90 },
    { url: `${base}/blog/best-ai-tools-for-seo-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.88 },
    { url: `${base}/blog/best-ai-chatbots-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.90 },
    { url: `${base}/blog/best-ai-productivity-tools-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.88 },
    // aiso-taaft-gaps sprint: SEO gap posts
    { url: `${base}/blog/free-chatgpt-alternatives-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.92 },
    { url: `${base}/blog/free-midjourney-alternatives-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.91 },
    { url: `${base}/blog/claude-vs-gemini`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.91 },
    { url: `${base}/blog/perplexity-vs-chatgpt-vs-google`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.90 },
    { url: `${base}/blog/free-grammarly-alternatives-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.92 },
    { url: `${base}/blog/free-github-copilot-alternatives-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.92 },
    { url: `${base}/blog/free-jasper-alternatives-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.91 },
    { url: `${base}/blog/free-cursor-alternatives-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.91 },
    // aiso-taaft-gaps sprint Apr 28 2026: 5 alternatives + 2 compare pages
    { url: `${base}/alternatives/figma`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.92 },
    { url: `${base}/alternatives/notion`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.92 },
    { url: `${base}/alternatives/trello`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.92 },
    { url: `${base}/alternatives/slack`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.92 },
    { url: `${base}/alternatives/airtable`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.92 },
    { url: `${base}/compare/cursor-vs-windsurf`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.91 },
    { url: `${base}/compare/n8n-vs-zapier`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.91 },
    // aiso-taaft-gaps sprint Apr 28 2026: high-SV alternatives blog posts
    { url: `${base}/blog/free-claude-alternatives-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.92 },
    { url: `${base}/blog/notion-ai-alternatives-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.92 },
    { url: `${base}/blog/canva-ai-alternatives-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.91 },
    // aiso-taaft-gaps sprint Apr 29 2026: writers guide + Gemini/Perplexity alternatives
    { url: `${base}/blog/best-ai-tools-for-writers-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.92 },
    { url: `${base}/blog/gemini-alternatives-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.92 },
    { url: `${base}/blog/perplexity-alternatives-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.91 },
    // aiso-taaft-gaps sprint Apr 29 2026: 31 missing blog posts added to sitemap
    { url: `${base}/blog/best-ai-coding-tools-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.90 },
    { url: `${base}/blog/best-ai-customer-service-tools-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.88 },
    { url: `${base}/blog/best-ai-data-analysis-tools-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.88 },
    { url: `${base}/blog/best-ai-design-tools-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.88 },
    { url: `${base}/blog/best-ai-image-generators-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.90 },
    { url: `${base}/blog/best-ai-marketing-tools-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.88 },
    { url: `${base}/blog/best-ai-tools-for-coaches-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-consultants-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-content-creators-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.88 },
    { url: `${base}/blog/best-ai-tools-for-content-marketers-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.87 },
    { url: `${base}/blog/best-ai-tools-for-ecommerce-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.88 },
    { url: `${base}/blog/best-ai-tools-for-executive-assistants-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-finance-accounting-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.86 },
    { url: `${base}/blog/best-ai-tools-for-hr-professionals-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-operations-managers-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-project-managers-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.87 },
    { url: `${base}/blog/best-ai-tools-for-sales-professionals-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.87 },
    { url: `${base}/blog/best-ai-tools-for-small-business-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.88 },
    { url: `${base}/blog/best-ai-tools-for-startups-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.88 },
    { url: `${base}/blog/best-ai-tools-for-students-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.90 },
    { url: `${base}/blog/best-ai-tools-for-teachers-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.87 },
    { url: `${base}/blog/best-ai-tools-for-virtual-assistants-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-video-generators-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.90 },
    { url: `${base}/blog/best-ai-writing-tools-comparison-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.88 },
    { url: `${base}/blog/best-api-monitoring-tools-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/chatgpt-vs-claude`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.93 },
    { url: `${base}/blog/chatgpt-vs-claude-vs-gemini`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.93 },
    { url: `${base}/blog/github-copilot-vs-cursor-vs-codeium`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.92 },
    { url: `${base}/blog/jasper-vs-copy-ai`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.90 },
    { url: `${base}/blog/midjourney-vs-dall-e`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.92 },
    { url: `${base}/blog/midjourney-vs-dalle-vs-stable-diffusion`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.91 },
    // aiso-taaft-gaps sprint Apr 29 2026: 3 new high-SV blog posts
    { url: `${base}/blog/best-ai-meeting-assistant-tools-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.90 },
    { url: `${base}/blog/best-ai-presentation-tools-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.90 },
    { url: `${base}/blog/best-ai-note-taking-apps-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.90 },
    { url: `${base}/blog/best-ai-email-tools-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.90 },
    { url: `${base}/blog/best-ai-search-engines-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.90 },
    { url: `${base}/blog/best-ai-automation-tools-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.90 },
    { url: `${base}/blog/best-ai-pdf-tools-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.90 },
    { url: `${base}/blog/best-ai-transcription-tools-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.90 },
    { url: `${base}/blog/best-ai-tools-for-youtubers-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.90 },
    // aiso-taaft-gaps sprint Apr 30 2026: 37 missing blog posts added to sitemap + 2 new posts
    { url: `${base}/blog/best-ai-agent-frameworks-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.90 },
    { url: `${base}/blog/best-ai-collaboration-tools-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.88 },
    { url: `${base}/blog/best-ai-crm-tools-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.88 },
    { url: `${base}/blog/best-ai-music-generators-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.90 },
    { url: `${base}/blog/best-ai-tools-for-academic-research-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.87 },
    { url: `${base}/blog/best-ai-tools-for-accountants-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.87 },
    { url: `${base}/blog/best-ai-tools-for-architects-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-copywriters-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.87 },
    { url: `${base}/blog/best-ai-tools-for-cybersecurity-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.88 },
    { url: `${base}/blog/best-ai-tools-for-data-scientists-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.88 },
    { url: `${base}/blog/best-ai-tools-for-designers-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.87 },
    { url: `${base}/blog/best-ai-tools-for-devops-engineers-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.87 },
    { url: `${base}/blog/best-ai-tools-for-doctors-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.86 },
    { url: `${base}/blog/best-ai-tools-for-engineers-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.87 },
    { url: `${base}/blog/best-ai-tools-for-financial-advisors-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.87 },
    { url: `${base}/blog/best-ai-tools-for-freelancers-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.88 },
    { url: `${base}/blog/best-ai-tools-for-game-developers-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.86 },
    { url: `${base}/blog/best-ai-tools-for-healthcare-professionals-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.87 },
    { url: `${base}/blog/best-ai-tools-for-journalists-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.87 },
    { url: `${base}/blog/best-ai-tools-for-lawyers-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.87 },
    { url: `${base}/blog/best-ai-tools-for-marketing-agencies-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.88 },
    { url: `${base}/blog/best-ai-tools-for-musicians-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.86 },
    { url: `${base}/blog/best-ai-tools-for-nonprofits-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.85 },
    { url: `${base}/blog/best-ai-tools-for-nurses-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.86 },
    { url: `${base}/blog/best-ai-tools-for-photographers-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.87 },
    { url: `${base}/blog/best-ai-tools-for-podcasters-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.87 },
    { url: `${base}/blog/best-ai-tools-for-product-managers-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.88 },
    { url: `${base}/blog/best-ai-tools-for-real-estate-agents-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.87 },
    { url: `${base}/blog/best-ai-tools-for-recruiters-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.86 },
    { url: `${base}/blog/best-ai-tools-for-social-media-managers-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.88 },
    { url: `${base}/blog/best-ai-tools-for-software-architects-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.86 },
    { url: `${base}/blog/best-ai-tools-for-translators-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.86 },
    { url: `${base}/blog/best-ai-tools-for-ux-designers-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.87 },
    { url: `${base}/blog/best-ai-tools-for-video-editors-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.88 },
    { url: `${base}/blog/miro-alternatives-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.91 },
    { url: `${base}/blog/free-notion-alternatives-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.93 },
    { url: `${base}/blog/chatgpt-vs-perplexity`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.93 },
    { url: `${base}/blog/best-ai-detector-tools-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.92 },
    { url: `${base}/blog/best-ai-resume-builders-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.91 },
    { url: `${base}/blog/best-ai-humanizer-tools-2026`, lastModified: now, changeFrequency: "weekly" as const, priority: 0.91 },
  ];

  const toolPages = tools.map((tool) => ({
    url: `${base}/tool/${tool.slug}`,
    lastModified: now,
    changeFrequency: "weekly" as const,
    priority: 0.8,
  }));

  const categoryPages = categories.map((cat) => ({
    url: `${base}/category/${cat.slug}`,
    lastModified: now,
    changeFrequency: "daily" as const,
    priority: 0.9,
  }));

  const comparisonPages = getAllComparisonPairs().map((pair) => ({
    url: `${base}/compare/${pair.slugA}-vs-${pair.slugB}`,
    lastModified: now,
    changeFrequency: "weekly" as const,
    priority: 0.75,
  }));

  const pricingPages = tools.map((tool) => ({
    url: `${base}/pricing/${tool.slug}`,
    lastModified: now,
    changeFrequency: "weekly" as const,
    priority: 0.85,
  }));

  const alternativesPages = getToolsWithAlternatives().map((tool) => ({
    url: `${base}/alternatives/${tool.slug}`,
    lastModified: now,
    changeFrequency: "weekly" as const,
    priority: 0.85,
  }));

  return [...staticPages, ...standaloneComparisons, ...categoryPages, ...toolPages, ...pricingPages, ...comparisonPages, ...alternativesPages];
}
