import { tools } from "@/data/tools";
import { getAffiliateUrl } from "@/data/affiliate-links";
import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Best AI Tools for Researchers 2026 - Academic Research & Literature Review",
  description:
    "Discover the best AI tools for researchers in 2026. Elicit, Semantic Scholar, Consensus, Scite, Research Rabbit, Connected Papers, and more. Accelerate literature reviews, paper analysis, and academic research.",
  keywords: [
    "best ai tools for researchers",
    "ai research tools",
    "ai for academic research",
    "ai tools for research papers",
    "ai literature review tools",
    "academic ai tools",
    "research assistant ai",
    "ai paper analysis",
    "systematic review ai",
  ],
  openGraph: {
    title: "Best AI Tools for Researchers 2026 - Academic Research & Literature Review",
    description:
      "The ultimate guide to AI tools for academic researchers. Compare Elicit, Semantic Scholar, Consensus, Scite, and 8+ specialized research tools.",
    url: "https://aisotools.com/best-ai-tools-for-researchers",
    type: "article",
  },
  alternates: {
    canonical: "https://aisotools.com/best-ai-tools-for-researchers",
  },
};

interface ResearchTool {
  name: string;
  slug: string;
  description: string;
  category: string;
  pricing: string;
  pricingDetails: string;
  strengths: string[];
  weaknesses: string[];
  bestFor: string;
  features: string[];
  researcherTip?: string;
}

const researchTools: ResearchTool[] = [
  {
    name: "Elicit",
    slug: "elicit",
    description: "AI research assistant that automates systematic literature reviews, extracts data from papers, and accelerates research synthesis with machine learning.",
    category: "Literature Review",
    pricing: "Freemium",
    pricingDetails: "Free (5,000 credits), Plus $10/mo, Pro $42/mo, Enterprise custom",
    strengths: [
      "Automates time-consuming literature reviews",
      "Extracts structured data from papers (methods, findings, sample sizes)",
      "Finds semantically similar papers beyond keyword matching",
      "Summarizes methodology and key findings instantly",
      "Excellent for systematic reviews and meta-analyses",
    ],
    weaknesses: [
      "Steep learning curve for advanced features",
      "Free tier credits run out quickly for large reviews",
      "Primarily optimized for empirical research papers",
    ],
    bestFor: "Systematic literature reviews, meta-analyses, empirical research, data extraction from papers",
    features: ["Automated literature search", "Data extraction", "Paper summarization", "Similar paper discovery", "Export to CSV"],
    researcherTip: "Use Elicit's columns feature to extract custom data points (e.g., 'sample size', 'methodology') across dozens of papers at once - saves hours of manual reading.",
  },
  {
    name: "Semantic Scholar",
    slug: "semantic-scholar",
    description: "AI-powered academic search engine from Allen Institute for AI that uses machine learning to understand research context and recommend highly relevant papers.",
    category: "Search & Discovery",
    pricing: "Free",
    pricingDetails: "Completely free for all features, no subscription required",
    strengths: [
      "210M+ research papers indexed across all disciplines",
      "AI-powered relevance ranking beyond citations",
      "TL;DR summaries generated by AI for quick understanding",
      "Citation context shows how papers cite each other",
      "Powerful filters (year, venue, field of study, open access)",
    ],
    weaknesses: [
      "Not all papers have AI-generated summaries yet",
      "Interface can feel overwhelming for new users",
      "Some niche journals may have limited coverage",
    ],
    bestFor: "Finding relevant papers, discovering influential research, citation analysis, cross-disciplinary searches",
    features: ["AI search", "Paper recommendations", "Citation graphs", "TL;DR summaries", "Research feeds"],
    researcherTip: "Create a research feed on your topic and check it weekly - Semantic Scholar's AI will surface newly published papers matching your interests before they gain citations.",
  },
  {
    name: "Consensus",
    slug: "consensus",
    description: "AI search engine that scans peer-reviewed research to answer questions with evidence-based consensus from scientific literature.",
    category: "Search & Discovery",
    pricing: "Freemium",
    pricingDetails: "Free (10 credits/mo), Premium $8.99/mo (unlimited), Enterprise custom",
    strengths: [
      "Synthesizes findings across multiple papers instantly",
      "Shows scientific consensus (e.g., '82% of studies support this claim')",
      "Cites actual peer-reviewed papers with links",
      "Excellent for evidence-based research questions",
      "Study snapshots provide quick methodology overviews",
    ],
    weaknesses: [
      "Free tier very limited (10 searches/month)",
      "Best for closed-ended research questions",
      "Primarily covers published research, not preprints",
    ],
    bestFor: "Evidence-based research, literature reviews, fact-checking claims, exploring research consensus",
    features: ["Consensus search", "Study snapshots", "Citation export", "Evidence synthesis", "Meter showing agreement"],
    researcherTip: "Use Consensus to quickly check if your hypothesis is supported by existing research before designing your study - it can save months of literature review.",
  },
  {
    name: "Scite",
    slug: "scite",
    description: "Smart citation tool that shows how publications have been cited, distinguishing between supporting, contrasting, and mentioning citations to reveal true research impact.",
    category: "Citation Analysis",
    pricing: "Freemium",
    pricingDetails: "Free limited access, Individual $20/mo, Student $10/mo, Institutional custom",
    strengths: [
      "Shows whether citations are supporting or contrasting",
      "Reveals if papers have been disputed or contradicted",
      "Browser extension for inline citation context",
      "Helps evaluate research reliability",
      "Excellent for critical literature reviews",
    ],
    weaknesses: [
      "Free tier very limited",
      "Student discount requires verification",
      "Not all papers have citation classification yet",
    ],
    bestFor: "Evaluating paper credibility, critical literature reviews, finding contradictory evidence, citation context",
    features: ["Smart citations", "Supporting/contrasting analysis", "Citation context", "Browser extension", "Reference checking"],
    researcherTip: "Before citing a highly-cited paper, check Scite to see if it's been contradicted - saves you from citing disputed findings in your own work.",
  },
  {
    name: "Research Rabbit",
    slug: "research-rabbit",
    description: "Interactive research mapping tool that visualizes paper connections, discovers related work, and helps build comprehensive literature collections through AI-powered recommendations.",
    category: "Literature Mapping",
    pricing: "Free",
    pricingDetails: "Completely free for researchers, no subscription required",
    strengths: [
      "Beautiful visual maps of research landscapes",
      "Discovers papers your keywords would miss",
      "Collaborative collections for research teams",
      "Alerts when new relevant papers are published",
      "Intuitive interface researchers actually enjoy using",
    ],
    weaknesses: [
      "Requires account creation",
      "Less useful for very new or niche topics",
      "Export options somewhat limited",
    ],
    bestFor: "Building comprehensive literature collections, discovering related research, research exploration, team collaboration",
    features: ["Visual paper maps", "Similar paper discovery", "Collections", "Alerts", "Collaboration"],
    researcherTip: "Start with 3-5 key papers in your field, add them to Research Rabbit, and explore the 'Earlier Works' and 'Similar Works' tabs - you'll find foundational papers you didn't know existed.",
  },
  {
    name: "Connected Papers",
    slug: "connected-papers",
    description: "Visual graph tool that creates citation-based maps showing how academic papers are connected, helping researchers explore their field and find seminal works.",
    category: "Literature Mapping",
    pricing: "Freemium",
    pricingDetails: "Free (5 graphs/mo), Premium $6.50/mo (unlimited graphs)",
    strengths: [
      "Instantly visualizes research landscape around any paper",
      "Identifies foundational and derivative works",
      "Color-coded by publication year for trend analysis",
      "No learning curve - paste DOI and explore",
      "Great for grant proposals and lit review visuals",
    ],
    weaknesses: [
      "Free tier limited to 5 graphs per month",
      "Graph quality depends on citation data availability",
      "Can't save multiple graphs on free tier",
    ],
    bestFor: "Finding seminal papers, exploring research fields, visualizing literature for presentations, discovering paper connections",
    features: ["Citation graphs", "Visual clustering", "Prior/derivative works", "Export graphs", "DOI/title search"],
    researcherTip: "Use Connected Papers to find 'bridge papers' that connect two subfields you're working across - these high-connection papers are gold for interdisciplinary research.",
  },
  {
    name: "ChatGPT / GPT-4",
    slug: "chatgpt",
    description: "OpenAI's versatile language model that assists researchers with brainstorming, writing, coding for data analysis, and explaining complex concepts.",
    category: "General Purpose",
    pricing: "Freemium",
    pricingDetails: "Free tier (GPT-3.5), Plus $20/mo (GPT-4, GPT-4o, advanced features)",
    strengths: [
      "Excellent for brainstorming research questions and hypotheses",
      "Helps structure papers and grant proposals",
      "Can write and debug data analysis code (Python, R)",
      "Explains statistical concepts clearly",
      "Assists with literature synthesis and summaries",
    ],
    weaknesses: [
      "Can generate plausible-sounding but incorrect information",
      "Not connected to academic databases in free tier",
      "Requires careful fact-checking for research use",
    ],
    bestFor: "Research brainstorming, writing assistance, data analysis coding, concept explanations, outlining papers",
    features: ["Conversational AI", "Code generation", "Writing assistance", "Data analysis", "Web browsing (Plus)"],
    researcherTip: "Use ChatGPT to generate R or Python code for statistical analyses, then verify the approach with a statistician - it's faster than Googling syntax and often suggests methods you hadn't considered.",
  },
  {
    name: "Claude",
    slug: "claude",
    description: "Anthropic's AI assistant with 200K+ token context window, exceptional for analyzing long research papers, synthesizing literature, and maintaining nuanced academic discussions.",
    category: "General Purpose",
    pricing: "Freemium",
    pricingDetails: "Free tier, Pro $20/mo (Claude 3.5 Sonnet, higher limits)",
    strengths: [
      "200K+ token context handles entire dissertations or multiple papers",
      "Superior reasoning for complex analytical tasks",
      "Excellent at identifying logical gaps and contradictions",
      "Nuanced understanding of methodology and research design",
      "Artifacts feature great for iterative writing",
    ],
    weaknesses: [
      "Free tier has usage limits",
      "No native academic database access",
      "Can be slower than ChatGPT on free tier",
    ],
    bestFor: "Analyzing long papers, systematic literature synthesis, complex reasoning tasks, research writing feedback",
    features: ["Long context window", "Document analysis", "Code generation", "Vision", "Artifacts", "Projects"],
    researcherTip: "Upload your entire manuscript to Claude and ask it to check for logical inconsistencies between sections - it excels at spotting when your introduction promises something your methods don't deliver.",
  },
  {
    name: "Perplexity",
    slug: "perplexity",
    description: "AI-powered research assistant that combines web search with language models to provide cited, sourced answers to research questions in real-time.",
    category: "Search & Discovery",
    pricing: "Freemium",
    pricingDetails: "Free tier, Pro $20/mo (GPT-4, unlimited searches, image upload)",
    strengths: [
      "Provides citations for every claim",
      "Real-time web search for current research",
      "Academic mode prioritizes scholarly sources",
      "Collections organize research by project",
      "Follow-up questions maintain context",
    ],
    weaknesses: [
      "Free tier has daily query limits",
      "Citation quality varies by topic",
      "Not as comprehensive as dedicated academic databases",
    ],
    bestFor: "Quick research questions, staying current, fact-checking, exploring new topics, sourced summaries",
    features: ["Cited answers", "Academic search", "Collections", "Follow-up questions", "Pro search (GPT-4)"],
    researcherTip: "Use Perplexity's Academic mode to get quick overviews of adjacent fields before diving deep - it's like having a colleague summarize another discipline's key concepts in minutes.",
  },
  {
    name: "Scholarcy",
    slug: "scholarcy",
    description: "AI-powered paper summarizer that automatically generates structured summaries, flashcards, and extracts key information from research articles and documents.",
    category: "Summarization",
    pricing: "Freemium",
    pricingDetails: "Free limited, Plus £7.99/mo (~$10), Library/University custom",
    strengths: [
      "Automatically extracts methods, findings, limitations",
      "Generates flashcards for key concepts",
      "Creates reference libraries with summaries",
      "Browser extension for instant summarization",
      "Exports to reference managers (Zotero, Mendeley)",
    ],
    weaknesses: [
      "Free tier limited to 3 articles/month",
      "Summary quality varies by paper structure",
      "Best for traditional empirical papers",
    ],
    bestFor: "Rapid paper screening, creating study materials, building reference libraries, systematic reviews",
    features: ["Auto summarization", "Flashcard generation", "Key info extraction", "Browser extension", "Reference export"],
    researcherTip: "Use Scholarcy during the initial screening phase of systematic reviews - process 50 abstracts in an hour to identify the 10 papers worth deep reading.",
  },
  {
    name: "Iris.ai",
    slug: "iris-ai",
    description: "AI assistant for systematic reviews and scientific text mining that helps researchers efficiently screen papers, extract data, and manage large-scale literature reviews.",
    category: "Literature Review",
    pricing: "Paid",
    pricingDetails: "Starting at €99/mo (~$108/mo) per user, Enterprise custom",
    strengths: [
      "Purpose-built for systematic reviews",
      "Automates PRISMA-compliant screening workflows",
      "Machine learning improves as you screen papers",
      "Extracts custom data fields across papers",
      "Collaboration features for review teams",
    ],
    weaknesses: [
      "No free tier - paid only",
      "Relatively expensive for individual researchers",
      "Learning curve for systematic review workflows",
    ],
    bestFor: "Systematic reviews, meta-analyses, institutional research teams, PRISMA-compliant reviews",
    features: ["Systematic review workflows", "ML-assisted screening", "Data extraction", "Team collaboration", "PRISMA export"],
    researcherTip: "If you're conducting a systematic review for publication, Iris.ai's PRISMA-compliant workflow and audit trail can save you from reviewer comments about screening methodology.",
  },
  {
    name: "Litmaps",
    slug: "litmaps",
    description: "Citation-based literature mapping tool that visualizes connections between papers, discovers new research, and alerts you to new publications in your field.",
    category: "Literature Mapping",
    pricing: "Freemium",
    pricingDetails: "Free (limited), Plus $8/mo, Team $12/user/mo",
    strengths: [
      "Beautiful, interactive citation maps",
      "Automatic alerts for new relevant papers",
      "Collaborative mapping for research teams",
      "Discovers papers through citation relationships",
      "Integrates with Zotero for reference management",
    ],
    weaknesses: [
      "Free tier limited to 1 map",
      "Requires seed papers to generate good maps",
      "Citation data quality varies by field",
    ],
    bestFor: "Building literature maps, staying current, team collaboration, discovering citation networks",
    features: ["Citation visualization", "Discovery alerts", "Team collaboration", "Zotero integration", "Seed-based mapping"],
    researcherTip: "Create a Litmap for your dissertation topic and set up weekly alerts - you'll discover new papers the moment they're published, keeping your literature review current.",
  },
];

// JSON-LD structured data for FAQs
const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "mainEntity": [
    {
      "@type": "Question",
      "name": "What are the best AI tools for academic research?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "The best AI tools for academic researchers include Elicit for automated literature reviews, Semantic Scholar for AI-powered paper search, Consensus for evidence-based research synthesis, Scite for smart citation analysis, Research Rabbit for literature mapping, and ChatGPT/Claude for research writing and analysis. Each tool excels at different research phases."
      }
    },
    {
      "@type": "Question",
      "name": "Can AI tools help with systematic literature reviews?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "Yes. Tools like Elicit, Iris.ai, and Scholarcy are specifically designed to accelerate systematic reviews. They automate paper screening, extract structured data across studies, and help manage PRISMA-compliant workflows. Elicit can process hundreds of papers in minutes, extracting methodology, findings, and sample sizes automatically."
      }
    },
    {
      "@type": "Question",
      "name": "Are AI research tools free for academics?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "Many offer free tiers: Semantic Scholar and Research Rabbit are completely free, Elicit has 5,000 free credits, Consensus offers 10 free searches monthly, and Connected Papers provides 5 free graphs per month. Several tools like Scite offer student discounts ($10/mo vs $20/mo). ChatGPT and Claude have generous free tiers for general research assistance."
      }
    },
    {
      "@type": "Question",
      "name": "How do AI tools help with literature reviews?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "AI tools accelerate literature reviews by: (1) finding relevant papers beyond keyword matching using semantic search, (2) automatically summarizing papers to identify relevance quickly, (3) extracting data points (methods, findings, sample sizes) across multiple papers, (4) visualizing citation networks to find foundational works, and (5) alerting you to newly published research in your field."
      }
    },
    {
      "@type": "Question",
      "name": "Can ChatGPT replace academic databases for research?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "No. ChatGPT is excellent for brainstorming, writing assistance, and explaining concepts, but it doesn't search academic databases and can generate plausible-sounding but incorrect citations. Use specialized tools like Semantic Scholar, Consensus, or Google Scholar for finding actual peer-reviewed papers, then use ChatGPT/Claude to help analyze and synthesize what you find."
      }
    },
    {
      "@type": "Question",
      "name": "What's the difference between Elicit and Consensus?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "Elicit is designed for in-depth systematic literature reviews with data extraction across papers, while Consensus answers specific research questions by synthesizing findings across studies. Use Elicit when you need to extract structured data from many papers (e.g., 'What were the sample sizes in mindfulness RCTs?'). Use Consensus for evidence-based questions (e.g., 'Does mindfulness reduce anxiety?')."
      }
    },
    {
      "@type": "Question",
      "name": "How can AI tools help with research paper writing?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "AI tools help with: outlining papers (ChatGPT/Claude), checking logical consistency across sections (Claude's long context), generating literature synthesis paragraphs (ChatGPT), writing and debugging data analysis code in R/Python (ChatGPT), and improving clarity and grammar (Grammarly). Always fact-check AI-generated content and maintain your own analytical voice."
      }
    },
    {
      "@type": "Question",
      "name": "Are there AI tools for finding contradictory research?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "Yes. Scite specializes in this - it classifies citations as supporting, contrasting, or mentioning, showing you when papers have been disputed or contradicted. This is invaluable for critical literature reviews and avoiding citing findings that have since been challenged. Connected Papers and Research Rabbit also help map research landscapes to identify debates."
      }
    }
  ]
};

export default function BestAIToolsForResearchersPage() {
  const toolsBySlug = new Map(tools.map((t) => [t.slug, t]));

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {/* Breadcrumb */}
        <nav className="text-sm text-gray-500 mb-6">
          <Link href="/" className="hover:text-white">
            Home
          </Link>
          <span className="mx-2">›</span>
          <span className="text-gray-300">Best AI Tools for Researchers</span>
        </nav>

        {/* Header */}
        <header className="mb-12">
          <h1 className="text-4xl md:text-5xl font-bold mb-4">
            Best AI Tools for Researchers 2026: Accelerate Academic Research
          </h1>
          <p className="text-xl text-gray-400 max-w-4xl">
            Comprehensive guide to AI tools transforming academic research. From automated
            literature reviews and citation analysis to paper discovery and research synthesis -
            discover how AI can accelerate your research workflow, save hundreds of hours, and
            uncover insights faster in 2026.
          </p>
          <div className="flex flex-wrap gap-2 mt-6">
            <span className="bg-blue-600/20 text-blue-400 px-3 py-1 rounded-full text-sm">
              Updated April 2026
            </span>
            <span className="bg-gray-800 text-gray-400 px-3 py-1 rounded-full text-sm">
              12 Essential Research Tools
            </span>
            <span className="bg-green-600/20 text-green-400 px-3 py-1 rounded-full text-sm">
              Free & Freemium Options
            </span>
          </div>
        </header>

        {/* Quick Navigation */}
        <section className="bg-gray-900 border border-gray-800 rounded-xl p-6 mb-12">
          <h2 className="text-lg font-semibold mb-3">Quick Navigation by Research Phase</h2>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div>
              <h3 className="text-sm font-medium text-gray-400 mb-2">📚 Literature Review</h3>
              <div className="space-y-1 text-sm">
                <a href="#elicit" className="text-blue-400 hover:text-blue-300 block">Elicit</a>
                <a href="#iris-ai" className="text-blue-400 hover:text-blue-300 block">Iris.ai</a>
                <a href="#scholarcy" className="text-blue-400 hover:text-blue-300 block">Scholarcy</a>
              </div>
            </div>
            <div>
              <h3 className="text-sm font-medium text-gray-400 mb-2">🔍 Search & Discovery</h3>
              <div className="space-y-1 text-sm">
                <a href="#semantic-scholar" className="text-blue-400 hover:text-blue-300 block">Semantic Scholar</a>
                <a href="#consensus" className="text-blue-400 hover:text-blue-300 block">Consensus</a>
                <a href="#perplexity" className="text-blue-400 hover:text-blue-300 block">Perplexity</a>
              </div>
            </div>
            <div>
              <h3 className="text-sm font-medium text-gray-400 mb-2">🗺️ Literature Mapping</h3>
              <div className="space-y-1 text-sm">
                <a href="#research-rabbit" className="text-blue-400 hover:text-blue-300 block">Research Rabbit</a>
                <a href="#connected-papers" className="text-blue-400 hover:text-blue-300 block">Connected Papers</a>
                <a href="#litmaps" className="text-blue-400 hover:text-blue-300 block">Litmaps</a>
              </div>
            </div>
            <div>
              <h3 className="text-sm font-medium text-gray-400 mb-2">✍️ Writing & Analysis</h3>
              <div className="space-y-1 text-sm">
                <a href="#chatgpt" className="text-blue-400 hover:text-blue-300 block">ChatGPT</a>
                <a href="#claude" className="text-blue-400 hover:text-blue-300 block">Claude</a>
                <a href="#scite" className="text-blue-400 hover:text-blue-300 block">Scite</a>
              </div>
            </div>
          </div>
        </section>

        {/* Introduction */}
        <section className="prose prose-invert max-w-none mb-16">
          <h2 className="text-3xl font-bold mb-4">How AI Is Transforming Academic Research</h2>
          <p className="text-gray-400 text-lg leading-relaxed mb-4">
            Academic research is experiencing a quiet revolution. AI tools are fundamentally changing
            how researchers discover papers, conduct literature reviews, analyze citations, and
            synthesize findings. What once took weeks now takes hours. What required reading hundreds
            of abstracts can now be automated with machine learning.
          </p>
          <p className="text-gray-400 text-lg leading-relaxed mb-4">
            From Elicit's automated systematic reviews to Semantic Scholar's AI-powered search,
            Scite's citation analysis to Research Rabbit's discovery algorithms - these tools don't
            just make research faster, they make it more comprehensive. They help you find papers
            your keywords would miss, identify contradictory findings before you cite them, and stay
            current as new research publishes.
          </p>
          <p className="text-gray-400 text-lg leading-relaxed mb-4">
            Whether you're a PhD student conducting your first literature review, a postdoc managing
            systematic reviews across hundreds of papers, or a PI keeping track of rapidly evolving
            fields - AI research tools have become essential infrastructure for modern academic work.
          </p>
          <p className="text-gray-400 text-lg leading-relaxed">
            This guide covers 12 specialized AI tools across literature review, search, citation
            analysis, mapping, and writing - complete with pricing, features, researcher tips, and
            use cases for different research phases.
          </p>
        </section>

        {/* Comparison Table */}
        <section className="mb-16">
          <h2 className="text-3xl font-bold mb-6">Quick Comparison: Research AI Tools</h2>
          <div className="overflow-x-auto">
            <table className="w-full bg-gray-900 border border-gray-800 rounded-xl">
              <thead className="bg-gray-800">
                <tr>
                  <th className="px-4 py-3 text-left text-sm font-semibold">Tool</th>
                  <th className="px-4 py-3 text-left text-sm font-semibold">Category</th>
                  <th className="px-4 py-3 text-left text-sm font-semibold">Pricing</th>
                  <th className="px-4 py-3 text-left text-sm font-semibold">Best For</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-800">
                {researchTools.map((tool) => (
                  <tr key={tool.slug} className="hover:bg-gray-800/50 transition">
                    <td className="px-4 py-3">
                      <a href={`#${tool.slug}`} className="font-medium text-blue-400 hover:text-blue-300">
                        {tool.name}
                      </a>
                    </td>
                    <td className="px-4 py-3 text-sm text-gray-400">{tool.category}</td>
                    <td className="px-4 py-3 text-sm text-gray-400">{tool.pricing}</td>
                    <td className="px-4 py-3 text-sm text-gray-400">{tool.bestFor.split(",")[0]}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        {/* Detailed Reviews */}
        <section className="mb-16">
          <h2 className="text-3xl font-bold mb-8">Detailed Reviews: Best AI Tools for Researchers</h2>
          <div className="space-y-12">
            {researchTools.map((tool, index) => {
              const toolData = toolsBySlug.get(tool.slug);
              return (
                <article
                  key={tool.slug}
                  id={tool.slug}
                  className="bg-gray-900 border border-gray-800 rounded-xl p-8 scroll-mt-24"
                >
                  <div className="flex items-start justify-between mb-4">
                    <div>
                      <div className="flex items-center gap-3 mb-2">
                        <h3 className="text-2xl font-bold">
                          {index + 1}. {tool.name}
                        </h3>
                        <span className="bg-gray-800 text-gray-400 px-3 py-1 rounded-full text-xs">
                          {tool.category}
                        </span>
                      </div>
                      <p className="text-gray-400">{tool.description}</p>
                    </div>
                    <div className="flex gap-2 shrink-0">
                      {(() => {
                        const affUrl = getAffiliateUrl(tool.slug) || (toolData?.affiliateUrl);
                        return affUrl ? (
                          <a
                            href={affUrl}
                            target="_blank"
                            rel="noopener noreferrer sponsored"
                            className="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg text-sm font-medium transition"
                          >
                            Try {tool.name} →
                          </a>
                        ) : null;
                      })()}
                      {toolData && (
                        <Link
                          href={`/tool/${tool.slug}`}
                          className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg text-sm font-medium transition"
                        >
                          View Tool →
                        </Link>
                      )}
                    </div>
                  </div>

                  <div className="grid md:grid-cols-2 gap-6 mt-6">
                    {/* Pricing */}
                    <div>
                      <h4 className="font-semibold text-gray-300 mb-2">💰 Pricing</h4>
                      <p className="text-gray-400 text-sm mb-1">{tool.pricing}</p>
                      <p className="text-gray-500 text-xs">{tool.pricingDetails}</p>
                    </div>

                    {/* Best For */}
                    <div>
                      <h4 className="font-semibold text-gray-300 mb-2">🎯 Best For</h4>
                      <p className="text-gray-400 text-sm">{tool.bestFor}</p>
                    </div>
                  </div>

                  {/* Strengths */}
                  <div className="mt-6">
                    <h4 className="font-semibold text-gray-300 mb-3">✅ Strengths</h4>
                    <ul className="grid md:grid-cols-2 gap-2">
                      {tool.strengths.map((strength, i) => (
                        <li key={i} className="text-gray-400 text-sm flex items-start">
                          <span className="text-green-400 mr-2 mt-0.5">•</span>
                          {strength}
                        </li>
                      ))}
                    </ul>
                  </div>

                  {/* Weaknesses */}
                  <div className="mt-6">
                    <h4 className="font-semibold text-gray-300 mb-3">⚠️ Limitations</h4>
                    <ul className="grid md:grid-cols-2 gap-2">
                      {tool.weaknesses.map((weakness, i) => (
                        <li key={i} className="text-gray-400 text-sm flex items-start">
                          <span className="text-yellow-400 mr-2 mt-0.5">•</span>
                          {weakness}
                        </li>
                      ))}
                    </ul>
                  </div>

                  {/* Features */}
                  <div className="mt-6">
                    <h4 className="font-semibold text-gray-300 mb-3">🔧 Key Features</h4>
                    <div className="flex flex-wrap gap-2">
                      {tool.features.map((feature, i) => (
                        <span
                          key={i}
                          className="bg-gray-800 text-gray-400 px-3 py-1 rounded-full text-xs"
                        >
                          {feature}
                        </span>
                      ))}
                    </div>
                  </div>

                  {/* Researcher Tip */}
                  {tool.researcherTip && (
                    <div className="mt-6 p-4 bg-blue-600/10 border border-blue-500/20 rounded-lg">
                      <p className="text-sm text-blue-200">
                        <strong className="text-blue-400">💡 Researcher Tip:</strong> {tool.researcherTip}
                      </p>
                    </div>
                  )}
                </article>
              );
            })}
          </div>
        </section>

        {/* AI Tools by Research Phase */}
        <section className="mb-16">
          <h2 className="text-3xl font-bold mb-6">AI Tools by Research Phase</h2>
          <div className="grid md:grid-cols-2 gap-6">
            <div className="bg-gray-900 border border-gray-800 rounded-xl p-6">
              <h3 className="text-xl font-semibold mb-3">📚 Literature Review Phase</h3>
              <ul className="space-y-2 text-gray-400">
                <li className="flex items-start">
                  <span className="text-blue-400 mr-2">→</span>
                  <span><strong>Elicit:</strong> Automate systematic reviews and data extraction</span>
                </li>
                <li className="flex items-start">
                  <span className="text-blue-400 mr-2">→</span>
                  <span><strong>Semantic Scholar:</strong> Find relevant papers with AI search</span>
                </li>
                <li className="flex items-start">
                  <span className="text-blue-400 mr-2">→</span>
                  <span><strong>Research Rabbit:</strong> Build comprehensive paper collections</span>
                </li>
                <li className="flex items-start">
                  <span className="text-blue-400 mr-2">→</span>
                  <span><strong>Scholarcy:</strong> Rapid paper screening and summarization</span>
                </li>
                <li className="flex items-start">
                  <span className="text-blue-400 mr-2">→</span>
                  <span><strong>Iris.ai:</strong> PRISMA-compliant systematic review workflows</span>
                </li>
              </ul>
            </div>

            <div className="bg-gray-900 border border-gray-800 rounded-xl p-6">
              <h3 className="text-xl font-semibold mb-3">🔬 Data Analysis & Synthesis</h3>
              <ul className="space-y-2 text-gray-400">
                <li className="flex items-start">
                  <span className="text-blue-400 mr-2">→</span>
                  <span><strong>ChatGPT:</strong> Write and debug data analysis code (Python, R)</span>
                </li>
                <li className="flex items-start">
                  <span className="text-blue-400 mr-2">→</span>
                  <span><strong>Claude:</strong> Analyze datasets and identify patterns</span>
                </li>
                <li className="flex items-start">
                  <span className="text-blue-400 mr-2">→</span>
                  <span><strong>Consensus:</strong> Synthesize findings across multiple studies</span>
                </li>
                <li className="flex items-start">
                  <span className="text-blue-400 mr-2">→</span>
                  <span><strong>Elicit:</strong> Extract structured data from papers</span>
                </li>
              </ul>
            </div>

            <div className="bg-gray-900 border border-gray-800 rounded-xl p-6">
              <h3 className="text-xl font-semibold mb-3">✍️ Writing & Manuscript Prep</h3>
              <ul className="space-y-2 text-gray-400">
                <li className="flex items-start">
                  <span className="text-blue-400 mr-2">→</span>
                  <span><strong>Claude:</strong> Analyze full manuscripts for logical consistency</span>
                </li>
                <li className="flex items-start">
                  <span className="text-blue-400 mr-2">→</span>
                  <span><strong>ChatGPT:</strong> Draft outlines, introductions, discussion sections</span>
                </li>
                <li className="flex items-start">
                  <span className="text-blue-400 mr-2">→</span>
                  <span><strong>Scite:</strong> Verify citations haven't been contradicted</span>
                </li>
                <li className="flex items-start">
                  <span className="text-blue-400 mr-2">→</span>
                  <span><strong>Connected Papers:</strong> Create visual literature review diagrams</span>
                </li>
              </ul>
            </div>

            <div className="bg-gray-900 border border-gray-800 rounded-xl p-6">
              <h3 className="text-xl font-semibold mb-3">📖 Citation Management</h3>
              <ul className="space-y-2 text-gray-400">
                <li className="flex items-start">
                  <span className="text-blue-400 mr-2">→</span>
                  <span><strong>Scite:</strong> Check if citations are supporting or contrasting</span>
                </li>
                <li className="flex items-start">
                  <span className="text-blue-400 mr-2">→</span>
                  <span><strong>Semantic Scholar:</strong> Citation context and influence analysis</span>
                </li>
                <li className="flex items-start">
                  <span className="text-blue-400 mr-2">→</span>
                  <span><strong>Connected Papers:</strong> Visualize citation networks</span>
                </li>
                <li className="flex items-start">
                  <span className="text-blue-400 mr-2">→</span>
                  <span><strong>Litmaps:</strong> Track citation paths and discoveries</span>
                </li>
              </ul>
            </div>

            <div className="bg-gray-900 border border-gray-800 rounded-xl p-6">
              <h3 className="text-xl font-semibold mb-3">🔔 Staying Current</h3>
              <ul className="space-y-2 text-gray-400">
                <li className="flex items-start">
                  <span className="text-blue-400 mr-2">→</span>
                  <span><strong>Research Rabbit:</strong> Alerts for new papers in your collections</span>
                </li>
                <li className="flex items-start">
                  <span className="text-blue-400 mr-2">→</span>
                  <span><strong>Litmaps:</strong> Weekly notifications for new publications</span>
                </li>
                <li className="flex items-start">
                  <span className="text-blue-400 mr-2">→</span>
                  <span><strong>Semantic Scholar:</strong> Research feeds for specific topics</span>
                </li>
                <li className="flex items-start">
                  <span className="text-blue-400 mr-2">→</span>
                  <span><strong>Perplexity:</strong> Monitor current research and preprints</span>
                </li>
              </ul>
            </div>

            <div className="bg-gray-900 border border-gray-800 rounded-xl p-6">
              <h3 className="text-xl font-semibold mb-3">🤝 Team Collaboration</h3>
              <ul className="space-y-2 text-gray-400">
                <li className="flex items-start">
                  <span className="text-blue-400 mr-2">→</span>
                  <span><strong>Research Rabbit:</strong> Shared collections for research teams</span>
                </li>
                <li className="flex items-start">
                  <span className="text-blue-400 mr-2">→</span>
                  <span><strong>Iris.ai:</strong> Collaborative systematic review workflows</span>
                </li>
                <li className="flex items-start">
                  <span className="text-blue-400 mr-2">→</span>
                  <span><strong>Litmaps:</strong> Team mapping and shared discoveries</span>
                </li>
              </ul>
            </div>
          </div>
        </section>

        {/* How We Evaluated */}
        <section className="mb-16 bg-gray-900 border border-gray-800 rounded-xl p-8">
          <h2 className="text-3xl font-bold mb-6">How We Evaluated These Tools</h2>
          <div className="space-y-4 text-gray-400">
            <p>
              We evaluated each AI research tool based on criteria that matter to working researchers:
            </p>
            <div className="grid md:grid-cols-2 gap-6 mt-6">
              <div>
                <h3 className="font-semibold text-gray-300 mb-2">⚡ Research Impact</h3>
                <p className="text-sm">
                  Does it meaningfully accelerate research workflows? Save actual hours? Help you
                  find papers or insights you'd otherwise miss?
                </p>
              </div>
              <div>
                <h3 className="font-semibold text-gray-300 mb-2">🎯 Accuracy & Reliability</h3>
                <p className="text-sm">
                  Are citations accurate? Do summaries capture key findings? Can you trust the
                  output for scholarly work?
                </p>
              </div>
              <div>
                <h3 className="font-semibold text-gray-300 mb-2">💰 Value for Academics</h3>
                <p className="text-sm">
                  Is there a functional free tier? Are paid tiers reasonably priced for graduate
                  students and early-career researchers?
                </p>
              </div>
              <div>
                <h3 className="font-semibold text-gray-300 mb-2">🔬 Disciplinary Coverage</h3>
                <p className="text-sm">
                  Does it work across disciplines or only in specific fields? How current is the
                  paper database?
                </p>
              </div>
              <div>
                <h3 className="font-semibold text-gray-300 mb-2">⚙️ Integration & Workflow</h3>
                <p className="text-sm">
                  Does it integrate with existing tools (Zotero, Mendeley)? Export citations? Fit
                  into real research workflows?
                </p>
              </div>
              <div>
                <h3 className="font-semibold text-gray-300 mb-2">📈 Learning Curve vs. Benefit</h3>
                <p className="text-sm">
                  Is the time investment to learn the tool worth the productivity gains? Can you
                  get value quickly?
                </p>
              </div>
            </div>
            <p className="mt-6 text-sm">
              Every tool in this guide has been tested with real research tasks: conducting
              literature reviews, screening papers, analyzing citations, and synthesizing findings.
              We prioritize tools that deliver concrete time savings and research quality improvements
              over flashy features.
            </p>
          </div>
        </section>

        {/* FAQ Section */}
        <section className="mb-16">
          <h2 className="text-3xl font-bold mb-6">Frequently Asked Questions</h2>
          <div className="space-y-6">
            <div className="bg-gray-900 border border-gray-800 rounded-xl p-6">
              <h3 className="text-lg font-semibold mb-2">What are the best AI tools for academic research?</h3>
              <p className="text-gray-400">
                The best AI tools for academic researchers include Elicit for automated literature
                reviews, Semantic Scholar for AI-powered paper search, Consensus for evidence-based
                research synthesis, Scite for smart citation analysis, Research Rabbit for literature
                mapping, and ChatGPT/Claude for research writing and analysis. Each tool excels at
                different research phases.
              </p>
            </div>

            <div className="bg-gray-900 border border-gray-800 rounded-xl p-6">
              <h3 className="text-lg font-semibold mb-2">Can AI tools help with systematic literature reviews?</h3>
              <p className="text-gray-400">
                Yes. Tools like Elicit, Iris.ai, and Scholarcy are specifically designed to
                accelerate systematic reviews. They automate paper screening, extract structured
                data across studies, and help manage PRISMA-compliant workflows. Elicit can process
                hundreds of papers in minutes, extracting methodology, findings, and sample sizes
                automatically.
              </p>
            </div>

            <div className="bg-gray-900 border border-gray-800 rounded-xl p-6">
              <h3 className="text-lg font-semibold mb-2">Are AI research tools free for academics?</h3>
              <p className="text-gray-400">
                Many offer free tiers: Semantic Scholar and Research Rabbit are completely free,
                Elicit has 5,000 free credits, Consensus offers 10 free searches monthly, and
                Connected Papers provides 5 free graphs per month. Several tools like Scite offer
                student discounts ($10/mo vs $20/mo). ChatGPT and Claude have generous free tiers
                for general research assistance.
              </p>
            </div>

            <div className="bg-gray-900 border border-gray-800 rounded-xl p-6">
              <h3 className="text-lg font-semibold mb-2">How do AI tools help with literature reviews?</h3>
              <p className="text-gray-400">
                AI tools accelerate literature reviews by: (1) finding relevant papers beyond
                keyword matching using semantic search, (2) automatically summarizing papers to
                identify relevance quickly, (3) extracting data points (methods, findings, sample
                sizes) across multiple papers, (4) visualizing citation networks to find foundational
                works, and (5) alerting you to newly published research in your field.
              </p>
            </div>

            <div className="bg-gray-900 border border-gray-800 rounded-xl p-6">
              <h3 className="text-lg font-semibold mb-2">Can ChatGPT replace academic databases for research?</h3>
              <p className="text-gray-400">
                No. ChatGPT is excellent for brainstorming, writing assistance, and explaining
                concepts, but it doesn't search academic databases and can generate plausible-sounding
                but incorrect citations. Use specialized tools like Semantic Scholar, Consensus, or
                Google Scholar for finding actual peer-reviewed papers, then use ChatGPT/Claude to
                help analyze and synthesize what you find.
              </p>
            </div>

            <div className="bg-gray-900 border border-gray-800 rounded-xl p-6">
              <h3 className="text-lg font-semibold mb-2">What's the difference between Elicit and Consensus?</h3>
              <p className="text-gray-400">
                Elicit is designed for in-depth systematic literature reviews with data extraction
                across papers, while Consensus answers specific research questions by synthesizing
                findings across studies. Use Elicit when you need to extract structured data from
                many papers (e.g., "What were the sample sizes in mindfulness RCTs?"). Use Consensus
                for evidence-based questions (e.g., "Does mindfulness reduce anxiety?").
              </p>
            </div>

            <div className="bg-gray-900 border border-gray-800 rounded-xl p-6">
              <h3 className="text-lg font-semibold mb-2">How can AI tools help with research paper writing?</h3>
              <p className="text-gray-400">
                AI tools help with: outlining papers (ChatGPT/Claude), checking logical consistency
                across sections (Claude's long context), generating literature synthesis paragraphs
                (ChatGPT), writing and debugging data analysis code in R/Python (ChatGPT), and
                improving clarity and grammar (Grammarly). Always fact-check AI-generated content
                and maintain your own analytical voice.
              </p>
            </div>

            <div className="bg-gray-900 border border-gray-800 rounded-xl p-6">
              <h3 className="text-lg font-semibold mb-2">Are there AI tools for finding contradictory research?</h3>
              <p className="text-gray-400">
                Yes. Scite specializes in this - it classifies citations as supporting, contrasting,
                or mentioning, showing you when papers have been disputed or contradicted. This is
                invaluable for critical literature reviews and avoiding citing findings that have
                since been challenged. Connected Papers and Research Rabbit also help map research
                landscapes to identify debates.
              </p>
            </div>
          </div>
        </section>

        {/* Related Articles */}
        <section className="mb-16">
          <h2 className="text-3xl font-bold mb-6">Related Articles</h2>
          <div className="grid md:grid-cols-3 gap-6">
            <Link
              href="/best-ai-tools-for-students"
              className="bg-gray-900 border border-gray-800 rounded-xl p-6 hover:border-blue-500 transition"
            >
              <h3 className="text-lg font-semibold mb-2">Best AI Tools for Students</h3>
              <p className="text-gray-400 text-sm">
                ChatGPT, Grammarly, Quillbot, Photomath, and more - AI tools to ace your studies.
              </p>
            </Link>
            <Link
              href="/category/writing"
              className="bg-gray-900 border border-gray-800 rounded-xl p-6 hover:border-blue-500 transition"
            >
              <h3 className="text-lg font-semibold mb-2">AI Writing Tools</h3>
              <p className="text-gray-400 text-sm">
                Explore AI writing assistants, grammar checkers, and content generation tools.
              </p>
            </Link>
            <Link
              href="/category/productivity"
              className="bg-gray-900 border border-gray-800 rounded-xl p-6 hover:border-blue-500 transition"
            >
              <h3 className="text-lg font-semibold mb-2">AI Productivity Tools</h3>
              <p className="text-gray-400 text-sm">
                Discover AI tools for note-taking, task management, and workflow automation.
              </p>
            </Link>
          </div>
        </section>

        {/* CTA */}
        <section className="bg-gradient-to-r from-blue-600/20 to-purple-600/20 border border-blue-500/20 rounded-2xl p-12 text-center">
          <h2 className="text-3xl font-bold mb-4">Explore More AI Tools</h2>
          <p className="text-gray-400 mb-6 max-w-2xl mx-auto">
            Discover hundreds more AI tools for writing, research, data analysis, and academic work.
          </p>
          <div className="flex gap-4 justify-center flex-wrap">
            <Link
              href="/"
              className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-lg font-medium transition"
            >
              Browse All Tools
            </Link>
            <Link
              href="/category/writing"
              className="bg-gray-800 hover:bg-gray-700 text-white px-6 py-3 rounded-lg font-medium transition"
            >
              Writing Tools →
            </Link>
            <Link
              href="/category/data-analysis"
              className="bg-gray-800 hover:bg-gray-700 text-white px-6 py-3 rounded-lg font-medium transition"
            >
              Data Analysis Tools →
            </Link>
          </div>
        </section>
      </div>
    </>
  );
}
